<?xml version="1.0" encoding="utf-8"?><Database Name="HUCANET2" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ASATA407\SQLEXPRESSJORGE;Initial Catalog=HUCANET2;Persist Security Info=True;User ID=sa" SettingsObjectName="HUCAGESTIONDEENFERMOS.Properties.Settings" SettingsPropertyName="HUCANET2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Enfermo" Member="Enfermo">
    <Type Name="Enfermo">
      <Column Name="Inscripcion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NombreApellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Numero de la SS]" Member="Numero_de_la_SS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>