--AÑADIR UN CLIENTE 
CREATE PROCEDURE AñadirCliente
@IDCLIENTE varchar(5),
@APELLIDOS varchar(30),
@NOMBRES varchar(30)
AS
INSERT INTO CLIENTE(IDCLIENTE,APELLIDOS,NOMBRES)
VALUES(@IDCLIENTE,@APELLIDOS,@NOMBRES)

EXEC AñadirCliente 'INFTEA','AZURE','MANUEL';