--PROCEDIMIENTO MOSTRAR TODA LA INFORMACION A PARTIR DE UN IDCLIENTE INTRODUCIDO
CREATE PROCEDURE MostrarIdCliente
@IDCLIENTE varchar(5)
AS
SELECT *
FROM CLIENTE
WHERE IDCLIENTE=@IDCLIENTE;

EXEC MostrarIdCliente 'ARMAD';