--CREO LAS TABLAS CON SUS PRIMARY KEY
CREATE TABLE CLIENTE(
IDCLIENTE varchar(5) PRIMARY KEY,
APELLIDOS varchar(30) NULL,
NOMBRES varchar(30) NULL,
)


CREATE TABLE MOVIMIENTO(
IDCUENTA varchar(5) NULL,
IDMOVIMIENTO varchar(5) PRIMARY KEY,
TIPO varchar(20) NULL,
MONTO float NULL,
FECHA date NULL,
)

CREATE TABLE CUENTA(
IDCLIENTE  varchar(5) NULL,
IDCUENTA varchar(5) PRIMARY KEY,
SALDO float NULL,
DIVISA varchar(20) NULL,
)

--RELACIONES ENTRE LAS TABLAS
--CLIENTE CON CUENTA
ALTER TABLE CUENTA ADD CONSTRAINT fk_Cuenta
FOREIGN KEY (IDCLIENTE)
REFERENCES CLIENTE (IDCLIENTE);

--MOVIMIENTO CON CUENTA
ALTER TABLE MOVIMIENTO ADD CONSTRAINT fk_Movimiento
FOREIGN KEY (IDCUENTA)
REFERENCES CUENTA (IDCUENTA);



--INSERTAMOS LOS DATOS DE LAS TABLAS
 --REGISTROS TABLA CLIENTE
 --INSERT INTO CLIENTE (IDCLIENTE,APELLIDOS,NOMBRES)
 --VALUES('','')


 INSERT INTO CLIENTE (IDCLIENTE,APELLIDOS,NOMBRES)
 VALUES('IKKMW','PEREZ','JUAN')

 INSERT INTO CLIENTE (IDCLIENTE,APELLIDOS,NOMBRES)
 VALUES('ARMAD','DE LA TORRE','MIGUEL')

 INSERT INTO CLIENTE (IDCLIENTE,APELLIDOS,NOMBRES)
 VALUES('INFMA','ARMADA','SEBASTIAN')

 INSERT INTO CLIENTE (IDCLIENTE,APELLIDOS,NOMBRES)
 VALUES('CLOGA','RODRIGUEZ','AMADOR')


 --REGISTROS TABLA CUENTA
 INSERT INTO CUENTA (IDCLIENTE,IDCUENTA,SALDO,DIVISA)
 VALUES('IKKMW',20021,1000,'EUROS')

 INSERT INTO CUENTA (IDCLIENTE,IDCUENTA,SALDO,DIVISA)
 VALUES('ARMAD',20032,1200,'EUROS')

 INSERT INTO CUENTA (IDCLIENTE,IDCUENTA,SALDO,DIVISA)
 VALUES('INFMA',20052,1500,'EUROS')


 INSERT INTO CUENTA (IDCLIENTE,IDCUENTA,SALDO,DIVISA)
 VALUES('CLOGA',20073,900,'EUROS')

 --REGISTROS TABLA MOVIMIENTOS
 INSERT INTO MOVIMIENTO(IDCUENTA,IDMOVIMIENTO,TIPO,MONTO,FECHA)
 VALUES(20021,30322,'INGRESO',1600,'20210101')


 INSERT INTO MOVIMIENTO(IDCUENTA,IDMOVIMIENTO,TIPO,MONTO,FECHA)
 VALUES(20032,30323,'RETIRAR',200,'20210301')

 INSERT INTO MOVIMIENTO(IDCUENTA,IDMOVIMIENTO,TIPO,MONTO,FECHA)
 VALUES(20052,30324,'INGRESAR',500,'20210716')

 INSERT INTO MOVIMIENTO(IDCUENTA,IDMOVIMIENTO,TIPO,MONTO,FECHA)
 VALUES(20073,30325,'PAGAR RECIBO',430,'20210513')

