#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormBANCOSQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BANCOSQL")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WindowsFormBANCOSQL.Properties.Settings.Default.BANCOSQLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AñadirCliente")]
		public int AñadirCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="VarChar(30)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRES", DbType="VarChar(30)")] string nOMBRES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE, aPELLIDOS, nOMBRES);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarIdCliente")]
		public ISingleResult<MostrarIdClienteResult> MostrarIdCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE);
			return ((ISingleResult<MostrarIdClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BuscarCliente")]
		public ISingleResult<BuscarClienteResult> BuscarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRES", DbType="VarChar(30)")] string nOMBRES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRES);
			return ((ISingleResult<BuscarClienteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarCliente")]
		public int EliminarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRES", DbType="VarChar(30)")] string nOMBRES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRES);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarClientes")]
		public ISingleResult<ListarClientesResult> ListarClientes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarClientesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ModificarCliente")]
		public int ModificarCliente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDCLIENTE", DbType="VarChar(5)")] string iDCLIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDOS", DbType="VarChar(30)")] string aPELLIDOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRES", DbType="VarChar(30)")] string nOMBRES)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDCLIENTE, aPELLIDOS, nOMBRES);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarCliente")]
		public ISingleResult<MostrarClienteResult> MostrarCliente()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MostrarClienteResult>)(result.ReturnValue));
		}
	}
	
	public partial class MostrarIdClienteResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public MostrarIdClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class BuscarClienteResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public BuscarClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class ListarClientesResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public ListarClientesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
	
	public partial class MostrarClienteResult
	{
		
		private string _IDCLIENTE;
		
		private string _APELLIDOS;
		
		private string _NOMBRES;
		
		public MostrarClienteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCLIENTE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string IDCLIENTE
		{
			get
			{
				return this._IDCLIENTE;
			}
			set
			{
				if ((this._IDCLIENTE != value))
				{
					this._IDCLIENTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDOS", DbType="VarChar(30)")]
		public string APELLIDOS
		{
			get
			{
				return this._APELLIDOS;
			}
			set
			{
				if ((this._APELLIDOS != value))
				{
					this._APELLIDOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRES", DbType="VarChar(30)")]
		public string NOMBRES
		{
			get
			{
				return this._NOMBRES;
			}
			set
			{
				if ((this._NOMBRES != value))
				{
					this._NOMBRES = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
